### Sync request with using Jetty Http Client
GET http://localhost:8082/api/blog/reactive/mono
Content-Type: application/json


###
GET http://localhost:8082/api/blog/reactive/flux
Content-Type: application/json
