version: "3.8.0"

services:
  spring-java17-service:
    build: ../../../spring-java17-service
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - JAVA_OPTS=-javaagent:/app/elastic-apm-agent-1.45.0.jar
      - ELASTIC_APM_SERVICE_NAME=spring-java17-service
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTIC_APM_ENVIRONMENT=development
      - ELASTIC_APM_ENABLED=true
      - ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS=true
    depends_on: ['apm-server']
